# Generated by Django 5.0.2 on 2024-03-07 12:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Required 64 characters or fewer.', max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Required 64 characters or fewer.', max_length=64, verbose_name='Last name')),
                ('patronymic_name', models.CharField(blank=True, help_text='Required 64 characters or fewer.', max_length=64, null=True, verbose_name='Patronymic name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Required 128 characters or fewer.', max_length=128, verbose_name='Full name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('age', models.CharField(choices=[('CHLD', 'child'), ('TNGR', 'teenager'), ('ADLT', 'adult'), ('OLDR', 'olderly')], default='ADLT', max_length=4, verbose_name='Age')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=1, verbose_name='Sex')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Latitutude, Longitude')),
                ('location_verbose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nearest Location')),
                ('disappearance_date', models.DateField(verbose_name='Disappearnce Date')),
                ('circumstances', models.TextField(blank=True, null=True, verbose_name='Circumstances of disapprance')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('internet_data', models.TextField(blank=True, null=True, verbose_name='Internet Data')),
                ('features', models.TextField(verbose_name='Features')),
                ('clothing', models.TextField(verbose_name='Clothing')),
                ('personal_belongings', models.TextField(verbose_name='Personal Belongings')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photos')),
                ('health_condition', models.TextField(verbose_name='Health condition')),
                ('alcohol', models.BooleanField(default=False, verbose_name='Alcohol')),
                ('drugs', models.BooleanField(default=False, verbose_name='Drugs')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('status', models.CharField(choices=[('O', 'Open'), ('A', 'Active'), ('C', 'Closed')], default='O', max_length=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='ReporterSearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(help_text='Required 32 characters or fewer.', max_length=32, verbose_name='Relationship')),
                ('additiona_info', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='search_requests.reporter', verbose_name='Reporter')),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_request', to='search_requests.searchrequest', verbose_name='Search Request')),
            ],
            options={
                'unique_together': {('reporter', 'search_request')},
            },
        ),
    ]
