# Generated by Django 5.0.3 on 2024-04-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveySearchRequest',
        ),
    ]
