# Generated by Django 5.0.3 on 2024-03-18 06:48

import django.contrib.gis.geos.point
import location_field.models.spatial
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0002_searchrequest_latitude_searchrequest_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), srid=4326, verbose_name='Latitutude, Longitude'),
        ),
    ]
