# Generated by Django 5.0.3 on 2024-04-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0003_survey_search_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='search_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_requests.searchrequest', verbose_name='Search Request'),
        ),
    ]
