# Generated by Django 5.0.3 on 2024-03-18 10:10

import django.contrib.gis.geos.point
import location_field.models.spatial
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0003_alter_searchrequest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='searchrequest',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(82.919782, 55.029738), srid=4326, verbose_name='Latitutude, Longitude'),
        ),
    ]
