# Generated by Django 5.0.3 on 2024-03-18 15:51

import django.contrib.gis.geos.point
import location_field.models.spatial
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0004_remove_searchrequest_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='location_verbose',
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='city',
            field=models.CharField(default='Novosibirsk', max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(82.919782, 55.029738), srid=4326),
        ),
    ]
