# Generated by Django 5.0.3 on 2024-03-19 11:22

import django.contrib.gis.geos.point
import location_field.models.spatial
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0005_remove_searchrequest_location_verbose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='reporters',
            field=models.ManyToManyField(through='search_requests.ReporterSearchRequest', to='search_requests.reporter'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='location',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(82.919782, 55.029738), srid=4326, verbose_name='Location'),
        ),
    ]
