# Generated by Django 5.0.3 on 2024-03-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0006_searchrequest_reporters_alter_searchrequest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='reporters',
        ),
        migrations.AlterField(
            model_name='reportersearchrequest',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to='search_requests.reporter', verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='reportersearchrequest',
            name='search_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporters', to='search_requests.searchrequest', verbose_name='Search Request'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='age',
            field=models.CharField(choices=[('CHLD', 'Child'), ('TNGR', 'Teenager'), ('ADLT', 'Adult'), ('OLDR', 'Olderly')], default='ADLT', max_length=4, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='city',
            field=models.CharField(help_text='Type city name to find coordinates on map', max_length=255, verbose_name='City'),
        ),
    ]
