# Generated by Django 5.0.3 on 2024-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0007_remove_searchrequest_reporters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='city',
            field=models.CharField(help_text='Type a city name to find coordinates on map', max_length=255, verbose_name='City'),
        ),
    ]
