# Generated by Django 5.0.3 on 2024-03-20 10:16

import web_dashboard.search_requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0008_alter_searchrequest_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=web_dashboard.search_requests.models.path_and_rename, verbose_name='Photos'),
        ),
    ]
