# Generated by Django 5.0.3 on 2024-03-22 15:30

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_requests', '0009_alter_searchrequest_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Required 64 characters or fewer.', max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Required 64 characters or fewer.', max_length=64, verbose_name='Last name')),
                ('patronymic_name', models.CharField(blank=True, help_text='Required 64 characters or fewer.', max_length=64, null=True, verbose_name='Patronymic name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('relationship', models.CharField(help_text='Required 32 characters or fewer.', max_length=32, verbose_name='Relationship')),
                ('additiona_info', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.RemoveField(
            model_name='reportersearchrequest',
            name='reporter',
        ),
        migrations.AlterUniqueTogether(
            name='reportersearchrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportersearchrequest',
            name='search_request',
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='reporter_contact_details',
            field=models.TextField(default='reporter@mail.com', verbose_name='Reporter contact details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='reporter_full_name',
            field=models.CharField(default='Gogi', help_text='Required 128 characters or fewer.', max_length=128, verbose_name='Reporter full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='reporter_has_reported_to_police',
            field=models.BooleanField(default=False, verbose_name='Has reporter reported to police'),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='reporter_relationship',
            field=models.CharField(default='Friend', help_text='Required 128 characters or fewer.', max_length=128, verbose_name='Reporter relationship to missing person'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SurveySearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='search_requests.searchrequest', verbose_name='Search Request')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to='search_requests.survey', verbose_name='Survey')),
            ],
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
        migrations.DeleteModel(
            name='ReporterSearchRequest',
        ),
    ]
