# Generated by Django 5.0.2 on 2024-03-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adress',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='Null', help_text='Required 255 characters or fewer.', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
