# Generated by Django 5.0.2 on 2024-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_adress_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='patronymic_name',
            field=models.CharField(blank=True, help_text='Required 64 characters or fewer.', max_length=64, null=True, verbose_name='Patronymic name'),
        ),
    ]
