# Generated by Django 5.0.6 on 2024-05-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_patronymic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, error_messages={'unique': 'User with such telegram id already exist.'}, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
