# Generated by Django 5.0.6 on 2024-05-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'User with such telegram id already exist.'}, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
