# Generated by Django 5.0.6 on 2024-06-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.SmallIntegerField(default=300, verbose_name='Time zone'),
        ),
    ]
