# Generated by Django 5.0.3 on 2024-04-12 15:06

import django.contrib.gis.geos.point
import django.db.models.deletion
import location_field.models.spatial
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_requests', '0004_alter_survey_search_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Available'), ('M', 'On mission'), ('R', 'Returning')], default='A', max_length=1, verbose_name='status')),
                ('departure_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Departure at')),
                ('return_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Return at')),
                ('nickname', models.CharField(help_text='Required 32 characters or fewer.', max_length=32, verbose_name='Nickname')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistics.crew', verbose_name='Crew')),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_requests.searchrequest', verbose_name='Search Request')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required 32 characters or fewer.', max_length=32, verbose_name='Title')),
                ('address', models.CharField(help_text='Required 128 characters or fewer.', max_length=128, verbose_name='Address')),
                ('coordinates', location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(82.919782, 55.029738), srid=4326, verbose_name='Coordinates')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_requests.searchrequest', verbose_name='Search Request')),
            ],
        ),
    ]
