# Generated by Django 5.0.3 on 2024-04-14 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_crew_nickname_crew_title'),
        ('search_requests', '0004_alter_survey_search_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='search_request',
        ),
        migrations.AddField(
            model_name='departure',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('A', 'Active'), ('C', 'Closed')], default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='task',
            name='departure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='logistics.departure', verbose_name='Departure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departure',
            name='search_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='search_requests.searchrequest', verbose_name='Search Request'),
        ),
    ]
