# Generated by Django 5.0.3 on 2024-04-19 04:02

import location_field.models.spatial
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_departure_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='coordinates',
            field=location_field.models.spatial.LocationField(srid=4326, verbose_name='Coordinates'),
        ),
    ]
