# Generated by Django 5.0.6 on 2024-05-09 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_departure_created_at_departure_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='crew',
        ),
        migrations.AddField(
            model_name='departure',
            name='crews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='logistics.crew', verbose_name='Crew'),
        ),
    ]
