# Generated by Django 5.0.6 on 2024-05-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_remove_departure_crew_departure_crews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='crews',
        ),
        migrations.AddField(
            model_name='crew',
            name='departure',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='crews', to='logistics.departure', verbose_name='Departure'),
            preserve_default=False,
        ),
    ]
