# Generated by Django 5.0.6 on 2024-05-24 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_crew_members_alter_crew_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='members',
        ),
        migrations.AddField(
            model_name='crew',
            name='passengers',
            field=models.ManyToManyField(related_name='passenger_crews', to=settings.AUTH_USER_MODEL, verbose_name='Passangers'),
        ),
    ]
