# Generated by Django 5.0.6 on 2024-05-26 10:05

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.geos import Point


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_alter_crew_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='crew',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pickup at'),
        ),
        migrations.AddField(
            model_name='crew',
            name='pickup_location',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), srid=4326, verbose_name='Pickup location'),
            preserve_default=False,
        ),
    ]
