# Generated by Django 5.0.6 on 2024-05-26 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_remove_crew_phone_number_crew_pickup_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='pickup_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 16, 56, 54, 416345), verbose_name='Pickup at'),
            preserve_default=False,
        ),
    ]
