# Generated by Django 5.0.6 on 2024-05-26 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_alter_crew_pickup_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='passengers_max',
            field=models.IntegerField(default=3, verbose_name='Max passengers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crew',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='passenger_crews', to=settings.AUTH_USER_MODEL, verbose_name='Passengers'),
        ),
    ]
