# Generated by Django 5.0.6 on 2024-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_crew_passengers_max_alter_crew_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('M', 'On mission'), ('R', 'Returning'), ('C', 'Completed')], default='A', max_length=1, verbose_name='status'),
        ),
    ]
